name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clippy and rustfmt
      run: rustup component add clippy rustfmt

    - name: Print the version of `rustc`
      run: rustc --version

    - name: Run rustfmt with check mode
      run: |
        shopt -s globstar
        rustfmt **/*.rs --check

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D clippy::pedantic -D clippy::all

    - name: Build
      run: cargo build

    - name: Build the doc for the lint related to the rustdoc
      run: cargo doc
